title: ledighedsdato.dk
email: simon@simplesystemer.dk

collections:
  konsulenter:
    output: true
    permalink: /konsulenter/:path/

defaults:
  -
    scope:
      path: "_konsulenter"
    values:
      layout: "konsulent"

